import { NextResponse } from 'next/server';
import { requireHotelAccess } from '@/lib/auth/guards';

function esc(input: unknown) {
  return String(input ?? '').replace(/[\\()]/g, '\\$&').slice(0, 180);
}

function money(value: unknown) {
  return Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function makePdf(lines: string[]) {
  const body = lines.map((line, i) => `BT /F1 ${i === 0 ? 20 : 11} Tf 50 ${790 - i * 24} Td (${esc(line)}) Tj ET`).join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${Buffer.byteLength(body)} >>\nstream\n${body}\nendstream`,
  ];
  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((obj, index) => {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${index + 1} 0 obj\n${obj}\nendobj\n`;
  });
  const xref = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach(offset => { pdf += `${String(offset).padStart(10, '0')} 00000 n \n`; });
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf, 'utf8');
}

export async function GET(_request: Request, context: any) {
  const params = await context.params;
  const paymentId = params.paymentId;
  const ctx = await requireHotelAccess(null);
  if (ctx.error) return ctx.error;

  const { data: payment, error } = await ctx.supabase
    .from('payments')
    .select('id,hotel_id,reservation_id,folio_id,amount,currency,payment_method,status,gateway,gateway_transaction_id,paid_at,created_at,reservations(reservation_code,guests(first_name,last_name,email,phone)),folios(id,balance,total_charges,total_payments),hotels(name,address,tax_id,vat_rate)')
    .eq('id', paymentId)
    .eq('hotel_id', ctx.hotelId)
    .single();

  if (error || !payment) return NextResponse.json({ error: 'Payment not found' }, { status: 404 });

  const guest = (payment as any).reservations?.guests;
  const hotel = (payment as any).hotels || ctx.hotel;
  const vatRate = Number(hotel?.vat_rate ?? 7);
  const total = Number((payment as any).amount || 0);
  const vat = Math.round((total * vatRate / (100 + vatRate)) * 100) / 100;
  const subtotal = total - vat;

  const lines = [
    'Maitri PMS Receipt / Tax Invoice',
    `Hotel: ${hotel?.name || 'Hotel'}`,
    `Address: ${hotel?.address || '-'}`,
    `Tax ID: ${hotel?.tax_id || '-'}`,
    `Payment ID: ${(payment as any).id}`,
    `Reservation: ${(payment as any).reservations?.reservation_code || '-'}`,
    `Guest: ${guest ? `${guest.first_name || ''} ${guest.last_name || ''}`.trim() : '-'}`,
    `Method: ${(payment as any).payment_method || '-'}  Status: ${(payment as any).status}`,
    `Paid at: ${(payment as any).paid_at || (payment as any).created_at}`,
    '----------------------------------------',
    `Subtotal: ${money(subtotal)} ${(payment as any).currency || 'THB'}`,
    `VAT ${vatRate}%: ${money(vat)} ${(payment as any).currency || 'THB'}`,
    `Total: ${money(total)} ${(payment as any).currency || 'THB'}`,
    '----------------------------------------',
    'Generated by Maitri PMS',
  ];

  const pdf = makePdf(lines);
  return new NextResponse(pdf, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `inline; filename="receipt-${paymentId}.pdf"`,
      'Cache-Control': 'no-store',
    },
  });
}
