import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireHotelAccess } from '@/lib/auth/guards';
import { createAdminClient } from '@/lib/supabase/server';
import { createCheckoutSession, createStripeCustomer } from '@/lib/billing/stripe';
import { getPlan, getStripePriceId } from '@/lib/billing/plans';
import { parseJson } from '@/lib/http/validation';
import { rateLimit, requireProductionSecret } from '@/lib/security/rate-limit';
const schema = z.object({ plan: z.enum(['starter', 'standard', 'pro', 'enterprise']) });
function appUrl() { if (process.env.NEXT_PUBLIC_APP_URL) return process.env.NEXT_PUBLIC_APP_URL; if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`; return 'http://localhost:3000'; }
export async function POST(request: Request) { try { const limited = await rateLimit(request, 'billing.checkout', 10, 60000); if (limited) return limited; const missingStripe = requireProductionSecret('STRIPE_SECRET_KEY'); if (missingStripe) return missingStripe; const parsed = await parseJson(request, schema); if (parsed.error) return parsed.error; const ctx = await requireHotelAccess(null, ['owner','admin']); if (ctx.error) return ctx.error; const plan = getPlan(parsed.data.plan); const priceId = getStripePriceId(plan.key); if (!priceId) return NextResponse.json({ error: `${plan.stripePriceEnv} is not configured` }, { status: 503 }); const admin = createAdminClient(); const { data: organization, error: orgError } = await admin.from('organizations').select('id, name, billing_email, stripe_customer_id').eq('id', ctx.profile.organization_id).single(); if (orgError || !organization) return NextResponse.json({ error: 'Organization not found' }, { status: 404 }); let customerId = organization.stripe_customer_id as string | null; if (!customerId) { const customer = await createStripeCustomer({ email: organization.billing_email || (ctx.user as any)?.email || undefined, name: organization.name, organizationId: organization.id }); customerId = customer.id; await admin.from('organizations').update({ stripe_customer_id: customerId }).eq('id', organization.id); } const session = await createCheckoutSession({ customerId, priceId, organizationId: organization.id, plan: plan.key, successUrl: `${appUrl()}/dashboard/billing?billing=success`, cancelUrl: `${appUrl()}/dashboard/billing?billing=cancelled` }); await admin.from('audit_logs').insert({ hotel_id: ctx.hotelId, user_id: ctx.user.id, action: 'billing.checkout.created', entity_type: 'organization', entity_id: organization.id, changes: { plan: plan.key, stripe_session_id: session.id } }); return NextResponse.json({ url: session.url }); } catch (error: unknown) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Billing checkout failed' }, { status: 500 }); } }
